### ISSUE TITLE
Doc component will look better if we add these classes to `<a>`

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#123]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/42554876/221426826-663ae36c-bf06-460e-8ddd-bebdcc54b454.png">

**Comment by TheHadiAhmadi** [comment]
Before
<img width="359" alt="image" src="https://user-images.githubusercontent.com/42554876/221426891-593df903-fd60-4d3e-ab9f-73af3420c07b.png">

After
<img width="399" alt="image" src="https://user-images.githubusercontent.com/42554876/221426873-2d075892-297d-4219-964e-e9ffb552966a.png">

**Comment by pournasserian** [comment]
I agree, please send PR
