### ISSUE TITLE
`$$restProps` should be passed to input element not `FormField`

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#177]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/42554876/221954237-bc14c7f4-a34d-4ffd-8b9e-3316bf14f589.png">

if user want to pass `min`, `max`, ... props, they should pass to `<input>` component.

**Comment by pournasserian** [comment]
@TheHadiAhmadi any update on this?

**Comment by TheHadiAhmadi** [comment]
@pournasserian didn't worked on it yet, I should define most used attributes/props for FormInput, FormSelect,....
