### ISSUE TITLE
add `key` or `getKey` prop for Select, CheckboxGroup, RadioGroup and Autocomplete

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#188]
```svelte
<script>
    import {Select} from 'yesvelte'


    let value1; // value will be: {key: 1, value: 'One'} but most of the time we need only 1
    let value2; // value will be: 1 (no problem)
    let value3; // value will be: 1 (no problem)

</script>

<Select bind:value={value1} items={[{key: 1, text: 'One'}, {key: 2, text: 'Two'}]} let:item>
    {item.text} ({item.key})
</Select>

<Select bind:value={value2} items={[{key: 1, text: 'One'}, {key: 2, text: 'Two'}]} getKey={item=>item.key} let:item>
    {item.text} ({item.key})
</Select>

<Select bind:value={value3} items={[{key: 1, text: 'One'}, {key: 2, text: 'Two'}]} key="key" let:item>
    {item.text} ({item.key})
</Select>

```

@pournasserian what do you think? should we add `key` prop or `getKey` prop? or do you have better suggestions?

**Comment by pournasserian** [comment]
I think it should be:

```
<Select bind:value={value3} items={[{key: 1, text: 'One'}, {key: 2, text: 'Two'}]} let:key let:item>
    {item.text} ({item.key})
</Select>
```

**Comment by TheHadiAhmadi** [comment]
@pournasserian when we want to bind value of select to some variable, after changing selected item variable should have 1 or 2 as value. But now there is no way for Select to know which field is the `key` of the selected item

```svelte
<Select bind:value={value3} items={[{theKey: 1, theText: 'One'}, {theKey: 2, theText: 'Two'}]} let:key let:item>
    {item.theText} ({item.theKey})
</Select>
```
In above example how we should tell that  `theKey` field of selected item should be sent to backend?

Thanks.

**Comment by pournasserian** [comment]
> @pournasserian when we want to bind value of select to some variable, after changing selected item variable should have 1 or 2 as value. But now there is no way for Select to know which field is the `key` of the selected item
> 
> ```svelte
> <Select bind:value={value3} items={[{theKey: 1, theText: 'One'}, {theKey: 2, theText: 'Two'}]} let:key let:item>
>     {item.theText} ({item.theKey})
> </Select>
> ```
> 
> In above example how we should tell that `theKey` field of selected item should be sent to backend?
> 
> Thanks.

@TheHadiAhmadi can't we say:
```
<Select bind:value={value3} items={[{theKey: 1, theText: 'One'}, {theKey: 2, theText: 'Two'}]} let:key={item.theKey} let:item>
    {item.theText} ({item.theKey})
</Select>
```

**Comment by TheHadiAhmadi** [comment]
@pournasserian let:key={item.theKey} is not valid syntax in svelte

https://svelte.dev/repl/a67a665f6dc04f029f1d2c3e4d08b6c1?version=3.55.1

```svelte
<Select let:key={theKey}>
     theKey is only available in this block
</Select>
```

**Comment by pournasserian** [comment]
> @pournasserian let:key={item.theKey} is not valid syntax in svelte
> 
> https://svelte.dev/repl/a67a665f6dc04f029f1d2c3e4d08b6c1?version=3.55.1
> 
> ```svelte
> <Select let:key={theKey}>
>      theKey is only available in this block
> </Select>
> ```

@TheHadiAhmadi correct. Then, I think this one is better:
```
<Select bind:value={value2} items={[{key: 1, text: 'One'}, {key: 2, text: 'Two'}]} key={item=>item.key} let:item>
    {item.text} ({item.key})
</Select>
```

What will be the issue if we bind JSON.stringify(item) of object to key inside of component?

**Comment by TheHadiAhmadi** [comment]
@pournasserian key always should be unique and I think there is no need to JSON.stringify it. if you want we can have `raw` prop which will bind to item object. 

```js
items= [{id: 1, name: "One"},{id: 1, name: "One"}] 
key = item => item.id

// After value changed
value = 1
raw = {id: 1, name: "One"}

```
