### ISSUE TITLE
Css bundle size

### ISSUE THREAD

**Issue by JericoFX** [yesvelte/yesvelte#208]
**Describe the bug**
First of all,  guys you are doing an amazing job, i love the style of yesvelte, and i know this is just the beginning, but i saw something, when i build the project the css is 1.3mb, like is using the entire css and i just have a button

**To Reproduce**
1. import anything
2. build it

**Expected behavior**
Just the necesary css is shipped

**Screenshots**
[image](https://prnt.sc/3vi6yQ61skKs)
**Desktop (please complete the following information):**
 - OS: Windows 11 lastest
 - Edge
 - ---

**Smartphone (please complete the following information):**

**Additional context**
nop

**Comment by pournasserian** [comment]
@JericoFX We have optimized the CSS in the latest version. Now the compressed/minified version is 65K for all components.

Here is the link:
https://unpkg.com/yesvelte@next/css/tabler.min.css

Also, if you want to use a few components and reduce the CSS size, you should compile the SCSS files. Here is the steps:

1. Clone the project
2. Review the below file and comment all components except a few components which you want to use: https://github.com/yesvelte/yesvelte/blob/dev/src/scss/tabler/_components.scss
3. Run `npm run style`: this will build your custom bundle

Please let me know if it covers your requirement.

**Comment by JericoFX** [comment]
Awesome, i will try it! thanks!
