### ISSUE TITLE
Develop Popup Component

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#213]

**Comment by TheHadiAhmadi** [comment]
Popup component is always bound to its previous element. is there any situation that user want to change `target` element?
https://svelte.ubeac.io/docs/components/popover/

is there any reason that user want to create popup/tooltip component like this?
```svelte
<Popup target="#my-button">Content of popup</Popup>
....
<Button id="my-button">show popup</Button>
```

**Comment by pournasserian** [comment]
@TheHadiAhmadi Isn't it better to have a `show` property for Popup?

**Comment by TheHadiAhmadi** [comment]
Yes it would be good, but without show prop Popup should work as expected and should bountld to target element.
