### ISSUE TITLE
Allow adding name attribute to input elements in Form components

### ISSUE THREAD

**Issue by nkrisc** [yesvelte/yesvelte#220]
**Is your feature request related to a problem? Please describe.**
It is cumbersome to use yesvelte Form components in a `<form>` that submits a POST using a form action. Data in yesvelte Form components aren't included in the request because they lack a `name` attribute on the `<input>`s they contain, and don't expose a prop to add it.

**Describe the solution you'd like**
Add a `name` prop that adds the `name` attribute to the `<input>` elements in the Form components

```
<FormFileUpload name="upload"/>
```

**Describe alternatives you've considered**
I'm currently working around the issue with this undesirable approach:

```
<script>
    // imports
    let upload: FormFileUpload;
    onMount(() => {
        upload.$$.root.querySelector('input').name = "upload"
    })
</script>

<form method="POST" action="?/file" use:enhance>
    <FormFileUpload bind:this={upload}/>
    <Button type="submit">Upload</Button>
</form>
```

**Comment by TheHadiAhmadi** [comment]
hi @nkrisc thanks for opening issue, We are working on this feature/bug in #200. until we fix this problem, you can use `FormField` + `FileUpload` components like this:

```svelte
<script>
    import {FormField, FileUpload} from 'yesvelte'

</script>
<form method="POST" action="?/file" use:enhance>
    <FormField label="Upload:">
        <FileUpload name="upload"/>
    </FormField>
</form>

```

**Comment by nkrisc** [comment]
And here I thought I had checked everything first to see if I was missing something. I missed the fact that the non-Form input components do in fact allow adding `name`. Thank you for pointing me in the right direction.
