### ISSUE TITLE
UI issue in Slider component for vertical mode

### ISSUE THREAD

**Issue by pournasserian** [yesvelte/yesvelte#225]
The Slider component's UI/CSS is not useful in vertical mode. Is there any use-case that we want to use Slider and FormSlider in vertical mode? If not, remove the feature from components and documentation site.

![image](https://user-images.githubusercontent.com/24959477/224558201-9febb7f0-df21-44a5-8933-693b0420240d.png)

**Comment by TheHadiAhmadi** [comment]
@pournasserian we can make its direction bottom-to-top with `direction: 'rtl'` option, should we do this for vertical or remove vertical feature?

also I don't know any usecase for vertical sliders.

**Comment by pournasserian** [comment]
> @pournasserian we can make its direction bottom-to-top with `direction: 'rtl'` option, should we do this for vertical or remove vertical feature?
> 
> also I don't know any usecase for vertical sliders.

For this milestone, just remove the vertical.
