### ISSUE TITLE
Issue in Repl while using ProgressBar component

### ISSUE THREAD

**Issue by pournasserian** [yesvelte/yesvelte#318]
Here is the repl code:

```svelte
<script>	
	import { Progress, ProgressBar } from 'yesvelte'
</script>

<svelte:head>
	<link rel="stylesheet" href="https://unpkg.com/yesvelte@next/css/tabler.min.css" />
</svelte:head>

<Progress>
	<ProgressBar value="25" />
</Progress>
```

It prompts:
```
'ProgressBar' is not exported by https://unpkg.com/yesvelte@0.0.2-next.0/index.js, imported by ./App.svelte
```

<img width="516" alt="image" src="https://user-images.githubusercontent.com/24959477/233716103-38491a47-4ebc-4a56-97e9-610e2b5844eb.png">

**Comment by TheHadiAhmadi** [comment]
@pournasserian we can fix this problem by merging Dev branch with main and release yesvelte@0.0.2 otherwise we can import components from `yesvelte@next`instead of `yesvelte`

**Comment by pournasserian** [comment]
> @pournasserian we can fix this problem by merging Dev branch with main and release yesvelte@0.0.2 otherwise we can import components from `yesvelte@next`instead of `yesvelte`

Thank you resolved
@mhmdtaherian please see this
