### ISSUE TITLE
Button -> `loading` doesn't have effect

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#337]

**Comment by pournasserian** [comment]
Please put screenshot

**Comment by TheHadiAhmadi** [comment]
Daisyui:
![image](https://user-images.githubusercontent.com/42554876/234059950-6ae8683d-6e7d-4903-b9ab-ab0e14fa2b75.png)

Tabler:
![image](https://user-images.githubusercontent.com/42554876/234059861-af6a7bfa-8baa-4fdf-a114-0e3542dd0f30.png)
