### ISSUE TITLE
CardFooter -> Should have some padding

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#338]

**Comment by pournasserian** [comment]
Please drop screenshot

**Comment by pournasserian** [comment]
Do we have padding in CardHeader?

**Comment by TheHadiAhmadi** [comment]
daisyui:
![image](https://user-images.githubusercontent.com/42554876/234060257-b0ae7d73-f5f8-4350-b548-9daf966cac81.png)

Tabler
![image](https://user-images.githubusercontent.com/42554876/234060387-fbfbd5ca-4a1c-477e-9bfa-2d5b0289f067.png)

**Comment by TheHadiAhmadi** [comment]
> Do we have padding in CardHeader?

Yes
