### ISSUE TITLE
CardHeader -> `light` prop doesn't have effect

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#345]
Daisyui:
![image](https://user-images.githubusercontent.com/42554876/234063476-77e18388-018f-462b-8304-12c165081ead.png)

Tabler:
![image](https://user-images.githubusercontent.com/42554876/234063368-005e5d07-83dc-40e3-92bf-97e5302b1f63.png)

**Comment by saadeghi** [comment]
Fixed but this `light` name doesn't make sense because it's actually making the header darker not lighter (on both dark and light themes)
