### ISSUE TITLE
some examples have horizontal overflow

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#364]
![image](https://user-images.githubusercontent.com/42554876/234502092-f8628d0d-8a70-4b3d-a51c-983ef7b87738.png)

**Comment by TheHadiAhmadi** [comment]
Pagination, Dropdown

**Comment by abdolian** [comment]
I fixed the pagination problem.
And in the dropdown documentation we use a class that named `.flex-wrap` to wrap the components and it seems that it doesn't generate in the `/css/tabler.min.css`. Fix the output file to resolve this.
