### ISSUE TITLE
Docs (colors) - `light` color is darker than `dark` in dark mode

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#366]
![image](https://user-images.githubusercontent.com/42554876/234505859-f5e2979b-5941-49f8-9cd5-1ae245695256.png)

**Comment by pournasserian** [comment]
@TheHadiAhmadi this is the same as tabler's behavior. Should we change it? (i don't think so)

**Comment by TheHadiAhmadi** [comment]
I don't know, we can skip it for now or open issue in tabler repo.

**Comment by pournasserian** [comment]
Correct, please open an issue there to see what they say.
I'm closing this so.
