### ISSUE TITLE
Should we use Docs layout in Landing page too?

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#372]
this is not looking bad, we can remove inner header and update text sizes.
![image](https://user-images.githubusercontent.com/42554876/234647101-7ae83173-a2c2-4ce3-bfdf-d71e05b4ed4e.png)

**Comment by TheHadiAhmadi** [comment]
One benefit is that documentation links are accessible from landing page without need to click on `Get Started` button

**Comment by pournasserian** [comment]
We won't need the same layout for landing page.
@TheHadiAhmadi any idea? If not, close this issue.
