### ISSUE TITLE
Clicking on the top level item on a Sidebar opens a new tab instead of expanding/collapse the sub/nested items.

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#375]
**Describe the bug**
Clicking on the top level item ('Requests' in the below repl) it opens a new tab.

**To Reproduce**
https://svelte.dev/repl/87890d95b4744c7daa1b6eb31ff06b20?version=3.58.0

**Expected behavior**
Clicking on the top level item ('Requests' in the below repl) should just expand/collapse the nested items, shouldn't follow the link and open a new tab.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome

**Comment by TheHadiAhmadi** [comment]
Thanks @yan5 for the report, I've fixed it now. Please check above repl with `yesvelte@v0.0.2-next.123`.

let us know if there is any problem or close issue if problem is resolved.

**Comment by yan5** [comment]
Hi @TheHadiAhmadi thanks for the quick fix, it works now.
