### ISSUE TITLE
More events for Input, FormInput, Autocomplete, and FormAutocomplete components

### ISSUE THREAD

**Issue by pournasserian** [yesvelte/yesvelte#377]
Here is a couple of scenarios that are not supported by above components:

- User want to register and when the user enters the email address and tries to fill other information (focus out), we should call an api to check if the email has been used before or not.
- Assume that we have an api that searches for something and there is an Autocomplete component. The api call should be happen for users key presses.

It is mandatory to provide a few event for Input, FormInput, Autocomplete, and FormAutocomplete.

Also, the code examples should be shown in documentation section.

**Comment by TheHadiAhmadi** [comment]
these examples are added to site.
