### ISSUE TITLE
CSS property to TableHead doesn't work

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#393]
**Describe the bug**
CSS property to TableHead doesn't work

**To Reproduce**
https://svelte.dev/repl/baf6b3c8fca34cd1890c630c5cbcccb4?version=3.58.0

**Expected behavior**
TableHead background color should be 'azure'. But I'm not sure if I'm doing it correctly. I tried passing style as well, but it didn't work either. <TableHead  style="background-color:azure;">. Any idea how to get this done?

**Comment by pournasserian** [comment]
> **Describe the bug** CSS property to TableHead doesn't work
> 
> **To Reproduce** Steps to reproduce the behavior: https://svelte.dev/repl/baf6b3c8fca34cd1890c630c5cbcccb4?version=3.58.0
> 
> **Expected behavior** TableHead background color should be 'azure'. But I'm not sure if I'm doing it correctly. I tried passing style as well, but it didn't work either. . Any idea how to get this done?

As I see you have set the `bgColor` property to `TableHead` component. You should set the property for each `TableCell` component.

This will work:
```svelte
	<TableHead>
		<TableRow>
			<TableCell bgColor="azure">Name</TableCell>
			<TableCell>Title</TableCell>
		</TableRow>
	</TableHead>
```

**Comment by yan5** [comment]
@pournasserian thanks, it works now.
B/w the discord link doesn't seems to be working.
![image](https://user-images.githubusercontent.com/20642737/235386839-81229ec2-e0d5-4c8b-953b-b24ee3cd7485.png)

**Comment by yan5** [comment]
@pournasserian Thanks it works now
