### ISSUE TITLE
Discord link doesn't seems to be working

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#397]
**Describe the bug**
Discord link given in the home page doesn't seems to be working.

**To Reproduce**
![image](https://user-images.githubusercontent.com/20642737/235386907-5fd7ae7d-fb74-4854-b71d-16fce87b6861.png)

**Comment by pournasserian** [comment]
> **Describe the bug** Discord link given in the home page doesn't seems to be working.
> 
> **To Reproduce** ![image](https://user-images.githubusercontent.com/20642737/235386907-5fd7ae7d-fb74-4854-b71d-16fce87b6861.png)

Thank you for reporting the issue.

**Comment by pournasserian** [comment]
@yan5 please review if the issue is not resolved, re-open that.
