### ISSUE TITLE
Add an Event field to the docs

### ISSUE THREAD

**Issue by JericoFX** [yesvelte/yesvelte#408]
**Is your feature request related to a problem? Please describe.**
Im trying to use yesvelte and every time i try a component i hit a wall with the events, i need to read the component code to understand how i can achive an event

**Describe the solution you'd like**
A place on the docs with all the events that are present on the component

**Describe alternatives you've considered**
--

**Additional context**
You guys are awesome!

**Comment by JericoFX** [comment]
Like Slider doesnt have the on:change, or i cant find it

**Comment by TheHadiAhmadi** [comment]
One goal of yesvelte is that all components should forward all events. As a temporary solution we only forward `input`, `focus`, `blur`, `change` and `click` events for Form components. 

Another solution would be adding types of all supported events for components (as typescript)

@pournasserian what do you think? What should we do?

**Comment by JericoFX** [comment]
thats awesome, i just need to wrap everything in a form the problem is like i didnt find that information anywere so i was crazy looking around the code to figure it out why. Thanks!

**Comment by pournasserian** [comment]
> One goal of yesvelte is that all components should forward all events. As a temporary solution we only forward `input`, `focus`, `blur`, `change` and `click` events for Form components.
> 
> Another solution would be adding types of all supported events for components (as typescript)
> 
> @pournasserian what do you think? What should we do?

The easiest (maybe not the best) is using wildcard-event forwarding in the components (available in SMUI, SvelteUI.org, etc.). 
Second option is to define useful events (similar to what we have done for a few of them) for each component.

What do you guys think?

**Comment by abdolian** [comment]
In my opinion we need to all native events during the using of a component. wildcard-event forwarding one of the best solution.

**Comment by pournasserian** [comment]
> In my opinion we need to all native events during the using of a component. wildcard-event forwarding one of the best solution.

Would you like to proceed to implementation?

**Comment by TheHadiAhmadi** [comment]
@JericoFX We've merged forward events PR, now you can use all native events for components. (yesvelte-0.0.2-next.139)

P.S. Slider component currently doesn't support events, we'll work on it.

You can see an example for TableRow component here https://svelte.dev/repl/8a77be4efb0b418db5a8f492b305ce59?version=3.55.1

Thanks

**Comment by JericoFX** [comment]
i will try it, thanks guys, continue working on this awesome library!
