### ISSUE TITLE
Popover not to close when cursor move over Popover body when trigger= hover

### ISSUE THREAD

**Issue by JawadAzizi** [yesvelte/yesvelte#436]
&lt;Popover trigger="hover" /&gt;

the Popover opens when the cursor hovers but it closes when the cursor moves away of the component regardless of the  Popover body or else where.
Popover should not close when the cursor hovers over Popover body

**Comment by TheHadiAhmadi** [comment]
Thanks @JawadAzizi for reporting. We'll fix it soon.

https://stackoverflow.com/a/19684440 We can use Timeout to prevent closing Popover Immediately, and then cancel timeout if mouse is inside Popover content.
