### ISSUE TITLE
padding property of the modal component

### ISSUE THREAD

**Issue by MW1Z4RD** [yesvelte/yesvelte#439]
The CSS style configuration of the modal component causes the right side of the page to have padding when the modal is opened.

https://www.yesvelte.com/docs/modal

When clicking any button to open a modal, the page will slightly shift to the left. This is because the class .y-body-modal-show has a style that adds a padding-right: 16px configuration. If this configuration is disabled, the page will return to normal.

![movie](https://github.com/yesvelte/yesvelte/assets/104913036/97d3170c-f118-4774-ac3d-7afffd6f91fc)

**Comment by TheHadiAhmadi** [comment]
@MW1Z4RD thanks for the detailed report and solution. I've fixed this problem in #441.
