### ISSUE TITLE
Direct import tabler.min.css cause the page loading slower in dev mode

### ISSUE THREAD

**Issue by edhub** [yesvelte/yesvelte#444]
In the instruction in home page, it suggests to import tabler css directly:
```ts
import 'yesvelte/css/tabler.min.css'
```

After I imported the css, I noticed a small lag when refreshing the page in dev mode. 
This is a small issue, but since svelte is blazing fast, the small lag in dev mode make me think: is yesvelte bad in performance?

After digging for a little while, I found the whole css is packed into the html head. Every time I refresh the page, dev server pack it again. I looked around and finally found the solution, and it's simple, instead of dirrect import the css, only import url, like this:

```svelte
// +layout.svelte
<script>
	import tabler from 'yesvelte/css/tabler.min.css?url';
</script>

<svelte:head>
	<link rel="StyleSheet" href={tabler} />
</svelte:head>
```

Thanks for yesvelte, I like it.

**Comment by edhub** [comment]
BTW, to import with "?url", the tabler.min.css will be served directly in dev mode, no build step involved.

And when making a production build, it'll be processed by vite and a smaller file is produced with tree-shaking.

**Comment by TheHadiAhmadi** [comment]
Thanks, I didn't know about this.
