### ISSUE TITLE
use another DatePicker library instead of LitePicker

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#452]

**Comment by TheHadiAhmadi** [comment]
FlatPickr has `altInput` feature which can show date value in user friendly text, and bind value to `yyyy-mm-dd...` format.

**Comment by TheHadiAhmadi** [comment]
then DatePicker will have bind:value and bind:formattedValue props.

**Comment by pournasserian** [comment]
It seems that flastpickr is good:
https://flatpickr.js.org/
