### ISSUE TITLE
Allow '' also as possible value for InputStates

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#453]
Allow '' also as possible value for InputStates. This will help to have an initial value that is neither valid or invalid, such as default state of the input box for eg.

Currently the default input box in my form has a green tick mark. I'd like to start off without any mark and progressively mark it 'valid' or 'invalid'.
![image](https://github.com/yesvelte/yesvelte/assets/20642737/498e4686-2c27-4837-b4d9-1c8186a29fb1)

**Comment by TheHadiAhmadi** [comment]
@yan5 state prop also supports `undefined` as value, which is the default value.

in this example you can see three types of states:
https://svelte.dev/repl/60eec09cf925429c911936a49b9bb0e0?version=3.55.1

What do you think about this name (`undefined`)? do you have any other name in mind which we can use instead of `undefined`?

thanks

**Comment by yan5** [comment]
I'm using Typescript and typed the variable with `InputStates` which doesn't allow anything except `valid` or `invalid`. So having some `default` or `''` would be great.

`let state: InputStates = 'valid'`

For eg: if I remove the type 'InputStates' and initialize it with `''` as follows, then Typescript shows the error on the formInput.
![image](https://github.com/yesvelte/yesvelte/assets/20642737/2092d365-607b-40bb-92b3-33a941287034)

![image](https://github.com/yesvelte/yesvelte/assets/20642737/0b7c3b0f-52d6-4b78-8185-5fb86b67b2aa)

Hope its clear now.

**Comment by TheHadiAhmadi** [comment]
Also we can consider other states like Warning: https://stackoverflow.design/product/components/inputs/#validation-examples

**Comment by TheHadiAhmadi** [comment]
@yan5 Yes, now I realized that `InputStates` type only supports `valid` and `invalid` and nothing else, but Input component's `state` prop also supports `undefined` as valid value.


does this works for you if we add `undefined` to InputStates type as well?
```svelte
<script lang="ts">
    import {Input, type InputStates} from 'yesvelte'
    
    
    let state: InputStates = undefined

    function changeState(newState: InputState) {
        state = newState
    }
    
    // setState('valid')
    // setState('invalid')
    // setState() // default is undefined
</script>

<Input bind:value={...} {state} />
```


in most components we assume `undefined` is default value for props, for example colors, sizes, ....

adding 'default' to InputStates type is not hard, but if we decided to to that, we should consider this pattern for other components too. 

@pournasserian What do you think about default values of component props? is it okay to use 'undefined' or add 'default' value for props as well?

one other example could be color of 'Button', we can add 'default' to colors list as well

```svelte
<Button color="primary">Primary</Button> <!-- .y-button.y-button-color-primary -->
<Button>Default</Button> <!-- .y-button -->

<!-- after adding default -->
<Button color="default">Default</Button> <!-- .y-button.y-button-color-default -->
<Button>Also Default</Button> <!-- .y-button.y-button-color-default -->
```

**Comment by TheHadiAhmadi** [comment]
also you can use this code to make your state prop type-safe:
```svelte
<script lang="ts">
    import type {ComponentProps} from 'svelte'
    import { Input } from 'yesvelte'

    let state: ComponentProps<Input>['state'] = 'valid' // or 'invalid' or undefined
</script>
...
```

**Comment by yan5** [comment]
> ```svelte
> let state: InputStates = undefined
> ```

this shows below error.
![image](https://github.com/yesvelte/yesvelte/assets/20642737/230a8fa4-ca55-48b4-ada9-ca44f171d7f8)

**Comment by yan5** [comment]
@TheHadiAhmadi 

Below works, FYI.

let titleState: InputStates | undefined = undefined;

**Comment by TheHadiAhmadi** [comment]
> @TheHadiAhmadi
> 
> Below works, FYI.
> 
> let titleState: InputStates | undefined = undefined;

I close this Issue, the solution is to add `| undefined` to types (to enable undefined type in typescript).
