### ISSUE TITLE
Double 'show password' icon displayed on Sign-in widgets.

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#455]
Double 'show password' icon displayed on Sign-in widgets.

![image](https://github.com/yesvelte/yesvelte/assets/20642737/f2aa19c8-715e-4c66-a7d3-ebf58e2c92ea)

**Comment by TheHadiAhmadi** [comment]
@yan5 Can you send me link of this page?
in https://www.yesvelte.com/demo/authentication/sign-in I see only one Icon.

**Comment by yan5** [comment]
I'm seeing another 'show' icon the moment I start typing pwd. It's not a bug, but in the example, we don't need to show the explicit 'eye' icon. Coz the typing pwd shows another 'show' icon anyway.

**Comment by TheHadiAhmadi** [comment]
@yan5 Which Operating System and Browser do you use? I think this is a feature of the Browser that you are using.

Windows + Chrome doesn't have this feature.

**Comment by TheHadiAhmadi** [comment]
in Edge browser I can see the second eye icon.

**Comment by yan5** [comment]
Yes, on Edge (on Ubuntu)

**Comment by TheHadiAhmadi** [comment]
Will disable this Edge-only feature, because Chrome and firefox doesn't support this.
