### ISSUE TITLE
Icon aligned at the bottom

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#470]
Given below icon configuration, I'd expect the icon to be centred vertically. But its currently placed at the bottom.

![image](https://github.com/yesvelte/yesvelte/assets/20642737/8b34af09-2aba-4257-bff2-b1ad7907919d)

![image](https://github.com/yesvelte/yesvelte/assets/20642737/fc8e1102-310d-4344-8e11-5f6ffae9263b)

**Comment by TheHadiAhmadi** [comment]
this problem is related to #468, We'll work on it in upcoming days.

**Comment by TheHadiAhmadi** [comment]
Fixed in https://github.com/yesvelte/yesvelte/pull/475
