### ISSUE TITLE
column gap doesn't work as expected in a grid setup

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#490]
Consider below layout
```
<El row container gap="4">
  <El col="4"></El>
  <El col="8"></El>
</El>
```
This will bring second column (col=8) to the next row, which is not what one expects.
Whats expected is, this should honour the gap=4 while keeping 4 + 8 (12) columns on the same row.

ie. if I remove gap, all columns will be on same row.

In a grid setup, we should have ability to specify gap/gutter correctly.

**Comment by TheHadiAhmadi** [comment]
@yan5 `gap` is only useful for flex displays, and for this usage you should use `g="4"` instead of `gap="4"`

like this: https://svelte.dev/repl/9c090e88cc324628868d9960b0641671?version=3.55.1

**Comment by yan5** [comment]
@TheHadiAhmadi Thanks
