### ISSUE TITLE
Editor doesn't honour state values 'valid' or 'invalid' (reopen)

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#491]
Looks like the previous fix [(478)](https://github.com/yesvelte/yesvelte/pull/478) didn't work. The Editor still won't show red or green border/icon if we set state to 'valid' or 'invalid'.

**Comment by TheHadiAhmadi** [comment]
@yan5 did you updated package to latest version? state works as expected on Editor and FormEditor components.

you can see here: https://svelte.dev/repl/85abfa76220d46c0ba4aa63afeb6577f?version=3.55.1

**Comment by yan5** [comment]
@TheHadiAhmadi  ,

Yes my bad, I didn't update the css files.
