### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by JericoFX** [yesvelte/yesvelte#494]
**Is your feature request related to a problem? Please describe.**
I see the Modal Animation too slow and in some cases i prefer another tipe of animation

**Describe the solution you'd like**
maybe a prop of the animation name or even the duration.

**Describe alternatives you've considered**
Create the modal by miself and passing the values

**Additional context**
you guys are awesome!

**Comment by TheHadiAhmadi** [comment]
@JericoFX 
This is related to css, currently duration is 0.5s and I'll make it a little bit faster. 

You can customize it by writing your own css.
Here is a REPL: https://svelte.dev/repl/1a92a088762043609adddbda9de6839f?version=3.55.1

as you can see, using above 4 classes you can control how to animate components, all components support those classes for animation.

`.y-offcanvas-show-opening`, `.y-alert-show-closing`, '.y-el-show-open` .....

also you can see `_modal.scss`, `_offcanvas.scss` and other files to see how to write custom animations.

let me know if you want to know more about this.

thanks
