### ISSUE TITLE
ability to switch year in datepicker

### ISSUE THREAD

**Issue by goyatg** [yesvelte/yesvelte#502]
Currently we can switch months in the datepicker but not the year (at least in the official documentation there is no example where this is possible)
Without the ability to switch years, datepicker has limited application.

**Comment by TheHadiAhmadi** [comment]
Hi @devrav, we are using LitePicker and it doesn't support this feature, we are thinking about replacing it with another date-picker library.

Which library do you suggest?

thanks

**Comment by goyatg** [comment]
Hey @TheHadiAhmadi , while I do not know enough about any particular library to recommend but I think https://stwui.vercel.app/datepicker has a very nice date picker which can be used for reference.

**Comment by TheHadiAhmadi** [comment]
Thanks, I'll check it
