### ISSUE TITLE
FormDatePicker not taking litepicker options

### ISSUE THREAD

**Issue by yan5** [yesvelte/yesvelte#522]
Below config disabled dates until today.
```
<DatePicker
	bind:value={validUntil}
	options={{
		lockDaysFilter: (day) => {
			return new Date() > (day?.toJSDate() || new Date());
		},
		firstDay: 0,
		format:"YYYY-MM-DD"
	}}>
</DatePicker>

```
![image](https://github.com/yesvelte/yesvelte/assets/20642737/2abb9e85-493d-454c-afb6-71f42e17a2da)

But FormDatePicker with same config doesn't disable the dates until today.
![image](https://github.com/yesvelte/yesvelte/assets/20642737/18490376-b0cb-4529-bd3d-144d9fad1613)

**Comment by TheHadiAhmadi** [comment]
thanks @yan5 for report. I've fixed it.

and here is link to documentation: https://www.yesvelte.com/docs/form/form-datepicker#Options
