### ISSUE TITLE
Impossible to make background transparent in dark mode

### ISSUE THREAD

**Issue by JericoFX** [yesvelte/yesvelte#549]
**Describe the bug**

**To Reproduce**
 set the body style background-color:transparent !important; and nothing happend the background keeps dark, but if i do that in light mode the background actually get transparent (is for a personal Project )

**Expected behavior**
Make the background transparent

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version lastest

**Comment by TheHadiAhmadi** [comment]
@JericoFX 
I don't know what you are doing, but I changed background color of body to transparent and applied for both dark and light themes.

![image](https://github.com/yesvelte/yesvelte/assets/42554876/9eaf4426-386a-4c84-b965-e5b8aabbf72d)

as you can see background color is changed and in `computed` section background-color is `rgba(0, 0, 0, 0)`
