### ISSUE TITLE
Offcanvas without backdrop disables most of main page's components

### ISSUE THREAD

**Issue by nickolay** [yesvelte/yesvelte#555]
Most of components on the main page stop reacting to clicks once `Offcanvas` is activated. I believe this is only supposed to happen with `<Offcanvas backdrop>`, which provides the appropriate visual cues.

**To Reproduce**
1. Go to https://www.yesvelte.com/docs/offcanvas
2. Click on "Toggle offcanvas"
3. Hover the "Source" tab just above the button just clicked (note that it changes styling as if it can be clicked.)
4. Now try to click the "Source" tab
5. Note that the click doesn't register and the tab doesn't change due to the offcanvas being shown.

**Expected behavior**
The offcanvas component should not prevent the main page from reacting to the user's input unless `backdrop` is set to `true`.

**Desktop:**
 - OS: macOS
 - Browser: Firefox 117.0a1 (2023-07-05) 
 - Also tested: Chrome Version 114.0.5735.198 (Official Build) (x86_64)

**Additional context**
I thought this might be related to #538, so I tested an earlier version `0.0.2-next.189` (but with my own project, not with the exact steps above). The older version worked as expected. I then changed back to `0.0.2-next.202` and disabled the [the focus-trap#activate() call](https://github.com/yesvelte/yesvelte/commit/4296ce70ecd0ed202f10f2fafceb5a7c9fbab08b#diff-5db3e8abc04f12a156999b6107ed97642f684b76e8405dc063e5afd2eb1c9e59R74) in my node_modules/ folder. Once I figured out [how to get vite to pick up my changes](https://stackoverflow.com/a/75167336/1026), it fixed the problem as well.

**Comment by TheHadiAhmadi** [comment]
Hi @nickolay 
Sorry for this breaking change in Offcanvas. Offcanvas and Modal components have `autoClose` prop, if this is true, You can close Offcanvas using `Escape` key or by Clicking outside. backdrop and autoClose are not related to each other, and you can have Offcanvas which have backdrop but cannot be closed when clicked it's outside.

and because `focustrap` is active, there is no way to interact with other elements. how can we make it work as expected? should it be related to backdrop's value, or add new prop to manage focustrap?

**Comment by TheHadiAhmadi** [comment]
I fixed the problem, please check and let me know if the problem persists.

thanks

**Comment by nickolay** [comment]
Yep, disabling focustrap for offcanvas without backdrop fixes my problem -- thanks for the quick fix!

The reason I didn't make a PR myself was that I wasn't sure I understood how it's intended to work. In particular the reason for [these (now deleted) bits](https://github.com/yesvelte/yesvelte/pull/539/files#diff-5db3e8abc04f12a156999b6107ed97642f684b76e8405dc063e5afd2eb1c9e59L64-L71).

**Comment by TheHadiAhmadi** [comment]
Your'e welcome.
those codes were for focusing Offcanvas after it opens. currently we have similar code which uses focustrap's activate and deactivate.

we use timeout to wait until the open transition completes.
