### ISSUE TITLE
Remove console.log in animate.ts

### ISSUE THREAD

**Issue by enolgor** [yesvelte/yesvelte#565]
Can this be removed? It pollutes the console with unnecessary logs.

https://github.com/yesvelte/yesvelte/blob/97333614dfbb1fe0feb18dd758c110079a3dd8fd/src/lib/internal/animate.ts#L5

**Comment by TheHadiAhmadi** [comment]
@enolgor Thank you, I'll remove it now

**Comment by TheHadiAhmadi** [comment]
@enolgor in version `0.0.2-next.216` console.log is removed.

**Comment by enolgor** [comment]
@TheHadiAhmadi thanks!
